name: moviemaster
description: Movie Discovery App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0' # Оновлено мінімальну версію для пакету[citation:6]
  flutter: '>=3.24.0' # Оновлено мінімальну версію для пакету[citation:6]

dependencies:
  firebase_core: ^3.15.2
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.6.12
  google_sign_in: ^6.2.4
  flutter_secure_storage: ^9.0.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # UI & Themes
  google_fonts: ^6.1.0
  shimmer: ^3.0.0

  # State Management & Navigation
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  go_router: ^12.1.3

  # Network
  dio: ^5.3.3
  logger: ^2.0.2

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.0

  # Images
  cached_network_image: ^3.3.0

  # Dependency Injection
  get_it: ^7.6.4
  flutter_dotenv: ^5.1.0

  # Для сторінки деталей: стабільний пакет для YouTube
  youtube_player_iframe: ^5.2.2 # Оновлена, стабільна версія[citation:3][citation:6]
  url_launcher: ^6.2.2
  dartz: ^0.10.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  flutterfire_cli: ^1.3.1
  mockito: ^5.4.0
  bloc_test: ^9.1.5
  mocktail: ^1.0.4
  hive_test: ^1.0.1

  integration_test:
    sdk: flutter

  test_cov_console: ^0.2.2
  fake_cloud_firestore: ^3.1.0
flutter:
  uses-material-design: true
  assets:
    - .env
flutter_test:
  integration_test:
    - integration_test/app_flow_test.dart